### ISSUE TITLE
MINEMOBS

### ISSUE THREAD

**Issue by Chocodu31** [Les3soleils/Fugucraft#3]
=======Pack Info======= 

IGN: UnbreakingSlime
Pack Version: 0.1.5
MC Version: 1.12.2
Forge Version: 14.23.5.2847
Mods Loaded: 219

=======System Info======= 

Operating System: Windows Vista
Java: 1.8.0_221 64bit
CPU: 8x Intel(R) Core(TM) i7 CPU 920 @ 2.67GHz
Display: GeForce GTX 960/PCIe/SSE2
Mem:  59% 2683/4530MB
Allocated:  92% 4181MB

======= Issue ======= 
 
Title: Minemobs
 
--------------------------- 
Description: Minemobs est un con, il est senser être intéligent, il vole l'argent de jerome226

=======CrashLog======= 
No CrashLog

**Comment by Minemobs** [comment]
ba ui lozik
